# Problem 41
 [Source](https://projecteuler.net/problem=41)

We shall say that an $n$-digit number is pandigital if it makes use of all the digits $1$ to $n$ exactly once. For example, $2143$ is a $4$-digit pandigital and is also prime.

What is the largest $n$-digit pandigital prime that exists?

In [ ]:
# Problem 41 workspace

## Answer:

___

# Problem 42
 [Source](https://projecteuler.net/problem=42)

The $n$
th
term of the sequence of triangle numbers is given by, $t\_n = \frac12n(n+1)$; so the first ten triangle numbers are:
$$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \dots$$

By converting each letter in a word to a number corresponding to its alphabetical position and adding these values we form a word value. For example, the word value for SKY is $19 + 11 + 25 = 55 = t\_{10}$. If the word value is a triangle number then we shall call the word a triangle word.

Using
[words.txt](resources/documents/0042_words.txt)
(right click and 'Save Link/Target As...'), a 16K text file containing nearly two-thousand common English words, how many are triangle words?

In [ ]:
# Problem 42 workspace

## Answer:

___

# Problem 43
 [Source](https://projecteuler.net/problem=43)

The number, $1406357289$, is a $0$ to $9$ pandigital number because it is made up of each of the digits $0$ to $9$ in some order, but it also has a rather interesting sub-string divisibility property.

Let $d\_1$ be the $1$
st
digit, $d\_2$ be the $2$
nd
digit, and so on. In this way, we note the following:

* $d\_2d\_3d\_4=406$ is divisible by $2$
* $d\_3d\_4d\_5=063$ is divisible by $3$
* $d\_4d\_5d\_6=635$ is divisible by $5$
* $d\_5d\_6d\_7=357$ is divisible by $7$
* $d\_6d\_7d\_8=572$ is divisible by $11$
* $d\_7d\_8d\_9=728$ is divisible by $13$
* $d\_8d\_9d\_{10}=289$ is divisible by $17$

Find the sum of all $0$ to $9$ pandigital numbers with this property.

In [ ]:
# Problem 43 workspace

## Answer:

___

# Problem 44
 [Source](https://projecteuler.net/problem=44)

Pentagonal numbers are generated by the formula, $P\_n=n(3n-1)/2$. The first ten pentagonal numbers are:
$$1, 5, 12, 22, 35, 51, 70, 92, 117, 145, \dots$$

It can be seen that $P\_4 + P\_7 = 22 + 70 = 92 = P\_8$. However, their difference, $70 - 22 = 48$, is not pentagonal.

Find the pair of pentagonal numbers, $P\_j$ and $P\_k$, for which their sum and difference are pentagonal and $D = |P\_k - P\_j|$ is minimised; what is the value of $D$?

In [ ]:
# Problem 44 workspace

## Answer:

___

# Problem 45
 [Source](https://projecteuler.net/problem=45)

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

|  |  |  |  |  |
| --- | --- | --- | --- | --- |
| Triangle |  | $T\_n=n(n+1)/2$ |  | $1, 3, 6, 10, 15, \dots$ |
| Pentagonal |  | $P\_n=n(3n - 1)/2$ |  | $1, 5, 12, 22, 35, \dots$ |
| Hexagonal |  | $H\_n=n(2n - 1)$ |  | $1, 6, 15, 28, 45, \dots$ |

It can be verified that $T\_{285} = P\_{165} = H\_{143} = 40755$.

Find the next triangle number that is also pentagonal and hexagonal.

In [ ]:
# Problem 45 workspace

## Answer:

___

# Problem 46
 [Source](https://projecteuler.net/problem=46)

It was proposed by Christian Goldbach that every odd composite number can be written as the sum of a prime and twice a square.

$$\begin{align}
9 = 7 + 2 \times 1^2\\
15 = 7 + 2 \times 2^2\\
21 = 3 + 2 \times 3^2\\
25 = 7 + 2 \times 3^2\\
27 = 19 + 2 \times 2^2\\
33 = 31 + 2 \times 1^2
\end{align}$$

It turns out that the conjecture was false.

What is the smallest odd composite that cannot be written as the sum of a prime and twice a square?

In [ ]:
# Problem 46 workspace

## Answer:

___

# Problem 47
 [Source](https://projecteuler.net/problem=47)

The first two consecutive numbers to have two distinct prime factors are:

$$\begin{align}
14 &= 2 \times 7\\
15 &= 3 \times 5.
\end{align}$$

The first three consecutive numbers to have three distinct prime factors are:

$$\begin{align}
644 &= 2^2 \times 7 \times 23\\
645 &= 3 \times 5 \times 43\\
646 &= 2 \times 17 \times 19.
\end{align}$$

Find the first four consecutive integers to have four distinct prime factors each. What is the first of these numbers?

In [ ]:
# Problem 47 workspace

## Answer:

___

# Problem 48
 [Source](https://projecteuler.net/problem=48)

The series, $1^1 + 2^2 + 3^3 + \cdots + 10^{10} = 10405071317$.

Find the last ten digits of the series, $1^1 + 2^2 + 3^3 + \cdots + 1000^{1000}$.

In [ ]:
# Problem 48 workspace

## Answer:

___

# Problem 49
 [Source](https://projecteuler.net/problem=49)

The arithmetic sequence, $1487, 4817, 8147$, in which each of the terms increases by $3330$, is unusual in two ways: (i) each of the three terms are prime, and, (ii) each of the $4$-digit numbers are permutations of one another.

There are no arithmetic sequences made up of three $1$-, $2$-, or $3$-digit primes, exhibiting this property, but there is one other $4$-digit increasing sequence.

What $12$-digit number do you form by concatenating the three terms in this sequence?

In [ ]:
# Problem 49 workspace

## Answer:

___

# Problem 50
 [Source](https://projecteuler.net/problem=50)

The prime $41$, can be written as the sum of six consecutive primes:

$$41 = 2 + 3 + 5 + 7 + 11 + 13.$$

This is the longest sum of consecutive primes that adds to a prime below one-hundred.

The longest sum of consecutive primes below one-thousand that adds to a prime, contains $21$ terms, and is equal to $953$.

Which prime, below one-million, can be written as the sum of the most consecutive primes?

In [ ]:
# Problem 50 workspace

## Answer:

___